# Generated by Django 4.2.1 on 2023-05-30 18:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Student",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="EducationInformation",
            fields=[
                (
                    "student_id",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="education_information",
                        serialize=False,
                        to="student.student",
                    ),
                ),
                ("status", models.CharField(max_length=50)),
                ("university_name", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="FamilyInformation",
            fields=[
                (
                    "studnt_id",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="family_information",
                        serialize=False,
                        to="student.student",
                    ),
                ),
                ("father_name", models.CharField(max_length=50)),
                ("mother_name", models.CharField(max_length=50)),
                ("siblings", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="PersonalInformation",
            fields=[
                (
                    "student_id",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="personal_information",
                        serialize=False,
                        to="student.student",
                    ),
                ),
                ("dob", models.DateField(null=True)),
                ("bloodGroup", models.CharField(max_length=10)),
            ],
        ),
    ]
